
name: blue_assistant
description: Blue Assistant Flutter app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  speech_to_text: ^7.2.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
