workflows:
  android-workflow:
    name: Build Blue Assistant APK
    environment:
      java: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
