workflows:
  android-workflow:
    name: Build Blue Assistant APK
    environment:
      java: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
